index_url = 'https://edu.tatar.ru/'
diary_url = index_url + 'user/diary'
diary_day_url = diary_url + '/day?for='
term_url = diary_url + '/term?term='
login_url = index_url + 'logon'
login_process_url = index_url + 'start/logon-process'
logout_url = index_url + '/logoff'
